style.css
Applies the serif font stack to the entry content, along with Inter overwrites where needed (drop cap, some of the widget blocks, pull quotes, captions, cites).
This commit also includes the `NonBreakingSpaceOverride` solution used in Twenty Nineteen. It fixes the non-breaking space character in Hoefler Text being extra wide in Chrome by loading a font that includes only the `&nbsp;` character, replacing that character in Hoefler Text.
=> Add the serif font stack to entry content

functions.php
Updates the `twentytwenty_get_post_meta` function to check the current post type before outputting post meta. Only `post` outputs post meta by default, but the `twentytwenty_allowed_post_types_for_meta_output` filter can be used by child themes and plugins to set which post types should be able to output post meta.
=> Fix post meta output on pages

CONTRIBUTING.md
Adds the CONTRIBUTING.md file based on the one included in Twenty Nineteen.
Fixes #60.
=> Add CONTRIBUTING.md based on Twenty Nineteen

style.css
Modifies the top value of the `site-header` whenever the `admin-bar` is shown. Uses the height and the Media breakpoint core uses for the `admin-bar`
fix for #45
=> modify top value to fix admin-bar overlap

style.css
- Fix for select elements not showing the chevron in Firefox (fixes #86)
- Set tables to `table-layout: fixed`, and set the base table font size to 1.6rem (fixes #87)
- Amended `word-break: break-word` with `word-wrap: break-word`, for more extensive browser support (fixes #85)
=> Entry content fixes

parts/page-header.php
Fixes #76
When on single page/post, it is not necessary to have a link to the same page.
=> Remove post/page link when is_singular() is true

header.php
=> Use HTTPS Protocol

style.css
This PR removes `width: 100%` from the post thumbnail image element. As noted in #84, setting the width to 100% will cause small images to look blurry, and the intent of the user could also have been to display a small image to begin with. Images smaller than the container are centered.
Since images can now take up less than the full with of the container, the PR also moves the pseudo element which creates the halfway up white background from the → 1000px media query to the base CSS, making it appear in all screen sizes.
Since images thinner than the container will now be displayed in the center of the container, the featured media caption has been updated to be centered as well.
Fixes #84.
=> Remove width: 100% from featured image element

content.php
Changed the escape function used for `$featured_media_inner_classes` to use `esc_attr`
Fixes [#113](https://github.com/WordPress/twentytwenty/issues/113)
WordPress.org username - [hareesh-pillai](https://profiles.wordpress.org/hareesh-pillai/)
=> Changed escape function

functions.php, header.php
Moves the output of the skip link from `header.php` to the `wp_body_open` action, matching the approach that will be used [in Twenty Eleven](https://core.trac.wordpress.org/ticket/47891). This also makes sure that `wp_body_open()` is triggered right after the `<body>`.
=> Use `wp_body_open` for output of skip link

style.css
Removes custom styling for `select` elements. Partly because of the issues with inconsistent display of the `data:image` chevron (see #120 and #86), but also because it will save us some time and effort down the road with RTL support, a11y concerns and other issues with inconsistent appearance in different browsers.
Removing the custom styling also benefits useability in that it makes the `select` elements more distinguishable from regular inputs.
Fixes #120.
=> Remove custom styling for select elements

style.css
The theme does not use select2 CSS in the front end so we have to remove that unused CSS from theme style.css
<hr>
WordPress.org ID: mukesh27
=> Remove unused select2 CSS from style.css

functions.php
In functions.php, use `sanitize_hex_color()` to add proper escaping to theme mods colors.
Fixes #130
=> Sanitize hex color used in theme mods

footer.php
There is a consistency issue in "Powered by" translation string.
Translator's comment says: `/* Translators: %s = WordPress */` although the context attached to `esc_html_x()` says `Translators: %s = name of the theme developer`.
Fixes: #148
=> Fixes inconsistency in translator’s comment

functions.php, style.css
Fix for #184
Adds two `body_class`es if either avatars are shown (`.show-avatars`) or hidden (`.hide-avatars`) for comment authors
----
WordPress.org username: acosmin
=> Show or hide commenter avatar

functions.php
To avoid double loading, i.e. Plugins, third-party scripts, and styles should not be prefixed, here's some [background](https://github.com/grappler/wp-standard-handles). GH/WPORG username: emiluzelac
=> Use Standard Handles for scripts/styles

phpcs.xml.dist
Exclude the `FunctionCallSignature` sniff which forces function arguments on the separate line
Improves readability of the code.
=> Update coding standards

functions.php
Fix for #207
- FontAwesome version adjusted and changed to a `string` for use in `wp_register_style()`;
- Block editor style handle - replaced `_` with `-` for consistency;
=> functions.php - small adjustments

404.php, style.css
Updates the `.archive-title` `font-size` value to match the design (`2.4rem` on mobile, `3.2rem` on → 700px).
Fixes #266.
=> Update archive titles font-size to match design

style.css
Added top padding to the top of the 404 page, so it matches the structure of other pages. Fixes #263.
Before:
After:
=> Added missing top padding to 404 page

style.css
Includes a bunch of updates to the block-styles on the front-end (no editor styles).
- Base block margins
- Pullquote
- Blockquote
- Widget blocks (Latest Posts, Archive, Recent Comments)
- Group block
- Separator block (fixes #254)
The block styles have been tested with the updates to the `.alignleft` and `.alignright` classes included in #236 and #237.
- Added styling for nested emphasis (fixes #255)
- Removed removal of outline from base input styles (fixes #67, inputs with their own focus styles might need updating)
- Added styles for `big` and `small`, adjusted size of `code` (fixes #88)
=> Update block styles

functions.php
Moves some html outside of the translation function when forming the continue reading string.
Closes: #318
=> Move html outside of translation in the 'continue reading...' text.

inc/custom-css.php
Fixes #322 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
=> UPDATE #322: Add accent color to next and previous post navigation

style.css
Adjusts the margins on tablet to fix overflow. Fixes #315.
=> Fix .alignleft and .alignright on tablet and up

functions.php
Fix for #319 
- Wrong function for translation.
- the `Translators` comment isn't needed anymore.
@pattonwebz @carolinan
=> Fix for twentytwenty_read_more_tag()

CONTRIBUTORS.md, classes/class-twentytwenty-script-loader.php, functions.php, parts/classes/class-script-loader.php
This updates #30 to move the class to the `classes` folder, remove the return type on the function and moves the instantiation and filter add to be beside other theme-support type items.
Will close: #29
=> Issue/29 2/async defer javascript

assets/js/index.js
If `Show search in header` is not enabled and you click on any actionable item (like the menu toggle), the console will output: `Uncaught TypeError: Cannot read property 'classList' of null at HTMLDocument.<anonymous> (VM6903 index.js:209)`
This PR will fix that, it also adds checks for the other queried Elements.
=> JS TypeError fix when search modal is not enabled

assets/css/editor-style-classic.css
In anticipation of #363 being merged, this is the `assets/css/editor-style-classic.css` file updated per WordPress Coding Standards.
=> Update `assets/css/editor-style-classic.css` per WordPress Coding Standards

assets/css/editor-style-block.css
In anticipation of #363 being merged, this is the `assets/css/editor-style-block.css` file updated per WordPress Coding Standards.
=> Update `assets/css/editor-style-block.css` per WordPress Coding Standards

.editorconfig
This updates the `.editorconfig` to the latest WordPress version:
https://core.trac.wordpress.org/browser/trunk/.editorconfig
=> Update `.editorconfig` to latest WordPress version

README.md, readme.txt
Updates `readme.md` and `readme.txt` to include:
```
Inter Font
License: SIL Open Font License, 1.1, https://opensource.org/licenses/OFL-1.1
Source: https://rsms.me/inter/
FontAwesome Icons
License: SIL Open Font License, 1.1, https://opensource.org/licenses/OFL-1.1
Source: https://www.fontawesome.io
FontAwesome Code
License: MIT License, https://opensource.org/licenses/MIT
Source: https://www.fontawesome.io
```
=> Update readme with licensing information for Inter and FontAwesome

footer.php
Footer only with social links:
Should we move with CSS the links to the right?
Footer with both menu and social links:
Footer with no footer menu or social links
=> #391 Fix - Display consistent social links on footer

404.php, index.php, searchform.php
Adds a first searchform.php template that gets used in the 404 template and the 'no posts found' search template. Labels and `aria-*` could use improvements.
The modal search form is unchanged by this PR. The styles on the other search also is unchanged. I've attached screenshots of the other searches in a widget, the no post found block and the 404 search block.
=> Add a searchform.php template

.travis.yml
Xdebug is only needed when generating code coverage reports, but when not needed, it really slows things down. Disabling it will speed up the build time.
Taken from : https://github.com/WordPress/twentynineteen/pull/464
=> Disable xdebug in Travis to speed up build time

package-lock.json, package.json
Another follow up to the `.editorconfig` update in #374 
This updates the `package.json` & `package-lock.json` files to uses _tabs_ instead of _spaces_ for indentation per WordPress Coding Standards
p.s I'd held of on creating this PR until there were no othher outstanding PRs where this would could merge conflicts 😬
=> Update `package.json` & `package-lock.json` per WordPress Coding Standards

inc/template-tags.php
=> Fixed - Two <h1> on static frontpage

.travis.yml, package.json
Another follow up to the _build tools_ update in #363
This updates the `package.json` format to match that of the WordPress Coding Standards
https://github.com/WordPress/gutenberg/tree/master/packages/npm-package-json-lint-config/
=> Update `package.json` format per WordPress Coding Standards

comments.php, functions.php, index.php, style.css, template-parts/navigation.php, template-parts/pagination.php
Updates the hr styling to make the base `hr` element more generic, and adds the theme specific style to all `hr` elements in `.entry-content` and all `hr` elements with a specific class, making the styling opt-in rather than opt-out.
Created after a discussion in #529.
=> Update `hr` styling to be less specific, and opt-in rather than opt-out

functions.php, style.css
Updates styled separators and entry content separators to use the secondary color (defaults to `#6d6d6d`) instead of the border color.
Partial fix for #533.
=> Updates separator elements to use the secondary a11y color

style.css
Updates the targeting to only hit the first article element, since the separator elements provide spacing between posts. Also updates the targeting to hit article elements that display pages or other non-post CPTs (in search results or on archive pages for custom post types).
Fixes #531.
=> Fix uneven post spacing on archive

header.php, style.css
Fixes the header toggle labels being cut off in IE 11. The fix required the header toggles to be set to `overflow: visible`, which resulted in the button SVGs causing a flex overflow issue on the body. That was fixed by wrapping the icons in new `.toggle-icon` elements with `overflow: hidden`.
Also fixes the modal social menu not wrapping correctly in IE, and updates the modal social menu to be aligned to the left on desktop (in all browsers), to match the design.
Fixes #348. #349 seems to be an unrelated issue.
=> Fix header toggle labels being cut off in IE11

footer.php, functions.php, inc/starter-content.php
This widget area ids from:
- `footer-one` -> `sidebar-1`
- `footer-two` -> `sidebar-2`
The labels remain the same as before.
These IDs are in line with other core themes and appear to be the most common configuration used by non-core themes as well.
Will close: #481
=> Swap widget area names to `sidebar-1` and `sidebar-2`

style-rtl.css, style.css, template-parts/content.php
Fixes https://github.com/WordPress/twentytwenty/issues/185
Took at a stab at it. I assume any changes in `style.css` should be reflected in `style-rtl.css` as well?
=> Made content full width when using Full Width template

assets/css/editor-style-classic.css, functions.php, style.css
Updates `:hover` selectors with a `:focus` pseudo-class selector
This is part of a pull request to follow adding the `a11y/selector-pseudo-class-focus` [stylelint-a11y rule](https://github.com/YozhikM/stylelint-a11y/tree/master/src/rules/selector-pseudo-class-focus) to check for accessibility issues
See https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html
=> Add `:focus` pseudo-class selector to `:hover` selectors

style.css
Drop-down category widget exceeds parent div on Twenty Twenty Theme.
[Before patch - exceeds parent div](https://prnt.sc/pb7uo7)
[After patch](https://prnt.sc/pb7v32)
=> Dropdown category widget exceeds parent div

assets/js/index.js, style.css
The previous implementation didn't work, and even if it did, it would have performance issues due to animating layout-invalidating properties like `height`.
This rewrite animates the menu using only opacity and transform, leading to smooth animations in most devices. The animation is JS-orchestrated, but entirely CSS-driven. The animation is skipped if a user has configured their OS or browser to reduce animations.
Note that the implementation is complex, but this is required complexity for smooth, cross-browser animations in a sliding menu scenario. When reviewing, **please consider whether this complexity is desirable, or whether it would be preferable to drop animations instead**.
This change also fixes issues with automatically opening sub-menus on page load.
Summary of changes:
- …
=> Fix animated menus.

template-parts/content-cover.php
Fixes #562 by moving the `screen-height` class to the `.cover-header-inner-wrapper` element. Also removes the `screen-width` class from the parent element, since it's not needed with the current structure.
=> Fix Cover Template header height in IE11

assets/js/customize-controls.js
This PR changes the way border colors get calculated to guarantee a `1.36:1` contrast with the background.
See https://github.com/WordPress/twentytwenty/issues/533#issuecomment-535991705 for details
=> Guarantee a 1.36:1 contrast for borders color

404.php, index.php, style.css, template-parts/modal-search.php
Converts the modal search to use the `get_serach_form()`.
Moves the `.modal-serach-form` class to the wrapper and changes the positioning rule to be ``.modal-serach-form form`.
On a quick test there seems to be no visual changes due to this. There is a small markup adjustment as a result but if that is a problem we can improve that in another PR. 
Closes: #219
=> Convert modal search to use `get_search_form()`

style.css, template-parts/modal-search.php
Fixes an issue where the search modal form doesn't have any left/right margins on tablets (as in the search field text goes to the edge of the screen). 
Also reduces the height of the search form to make it less dominant, which fixes #599.
=> Search modal form style adjustments

style.css
Removes the left margin from gallery block grid views.
Fixes: #605
=> Remove left margin from gallery grid view

style.css
Adds a top padding to the no search results form. Fixes #611. 
Also removes the bottom margin of the last paragraph in the `.archive-subtitle` element, since it was adding additional bottom spacing to the `.archive-header`.
=> Adjust spacing on archive pages

style.css
Improves the handling of long site titles by allowing the site title to wrap. Also sets a `max-width: 50%;` on the `.header-titles-wrapper` above 1000px, to guarantee a minimum amount of space for the navigation elements in the header.
Fixes #603.
=> Better handling of long site titles

classes/class-twentytwenty-walker-comment.php, functions.php, style.css
Updates the edit comment link to be less pronounced, and more distinctive from the reply button. Fixes #602.
**Before:**
**After:**
=> Update edit comment link to be less pronounced

header.php
Currently the theme has an HTML4 `meta` tag for `Content-Type`, but all of the core themes use the HTML5 `meta[charset]`, for example:
```php
<meta charset="<?php bloginfo( 'charset' ); ?>">
```
This PR aligns the `meta` tag with the other core themes.
=> Use HTML5 meta charset

style.css
Updates the targeting of widget titles to fix CSS not having any effect. Fixes #630.
Also adjusts the reset of the margin on the widget list items.
=> Fix widget margins for titles and list items

functions.php, inc/custom-css.php, style-rtl.css, style.css
Fixes the text color selected on the "Cover Template" Customizer panel not applying to the site header when a cover template is viewed. I thought there was an issue for this, but I can't find it now.
**Before:**
**After:**
=> Fix cover template text color setting not applying to the header

functions.php, style.css
Adds styles to adjust the spacing between some elements when the "Background Color" and "Header & Footer Background Color" settings are set to the same colors, using the `.reduced-spacing` class added in #582.
Combined with updates to the alignment classes in previous PRs, fixes #501.
**Before:**
**After:**
=> Reduce spacing when the same background color is set

style.css
This PR updates the mobile menu to cover the entire screen, and use the close button which is also displayed on desktop. Fixes #625.
**Before and after:**
=> Update the mobile menu to use the close button

404.php, footer.php, functions.php, inc/template-tags.php, index.php, singular.php, style.css, template-parts/footer-menus-widgets.php, templates/template-cover.php
This PR updates the footer structure per #564, based on the description by @afercia in #465.
The footer menus and widgets are moved to their own template part, `template-parts/footer-menus-widgets.php`, which is included in the bottom of the `<main>` element on all pages. That leaves the `<footer>` element with just the copyright text, "Powered by WordPress" and "To the top". 
Other changes:
- Changed the widget wrapper to an `aside` element with `role="complementary"`
- Added `role="navigation"` to the footer menu `nav` element
- Changed the `aria-label` on the footer menu `nav` element from "Footer menu" to just "Footer"
- Added a conditional body class indicating whether the top footer margin should be on the `<footer>` or on the `.footer-nav-widgets-wrapper`
- Fixes styling issue on …
=> Updated the footer structure

template-parts/modal-menu.php
Removed a conditional for `has_nav_menu( 'expanded' )` around the output of the "Close Menu" button, since the button should always be output now.
=> Removed conditional around output of close modal button

assets/js/index.js, header.php
Update the aria label for the horizontal menu from "Primary" to "Horizontal" so that the names on the front and admin match each other better.
Simplifies the markup for the menu by removing an extra div.
Fixes https://github.com/WordPress/twentytwenty/issues/73
=> Update aria label and markup for the horizontal menu

inc/template-tags.php
Updated the twentytwenty_edit_post_link to use the convention from twentynineteen and previous themes to have the post title available in screen reader text.
This changes the link from Edit This to Edit, but screen readers will get Edit Post Name.
=> Updated the twentytwenty_edit_post_link to use previous theme convention

header.php
Not a big deal, but `doctype` declaration should be the very first thing in the generated HTML document.
=> Doctype should be the very first character of the html page

searchform.php
The search query term is not visible in the search input field.
If we search any tern then it is visible in the search input.
E.g. If we search `testing` then it is visible in the search box.
See screenshot of theme Twenty Nineteen:
But, It is not visible in TwentyTwenty.
See screenshot - (Before Fix Theme TwentyTwenty):
---
The issue is in file `twentytwenty/searchform.php` line 24 the code is:
```
value="<?php get_search_query(); ?>"
```
This should be:
```
value="<?php echo get_search_query(); ?>"
```
After issue fix screenshot (After Fix Theme TwentyTwenty):
=> Fix: Search query term is not visible in the search input field

style-rtl.css, style.css
Instead of removing the RSS image, it would be better to remove the full link. Without that, the link will be vocalized as an empty link by assistive technologies. 
Worth noting I had to use `:first-of-type` pseudo selector since there is no specific class on this element.
Cheers,
Jb
=> RSS Widget: hide full link instead of just the related image

classes/class-twentytwenty-customize.php, classes/class-twentytwenty-walker-comment.php, comments.php, functions.php, header.php, template-parts/content-cover.php, template-parts/entry-author-bio.php, template-parts/entry-header.php, template-parts/featured-image.php, template-parts/footer-menus-widgets.php, template-parts/modal-menu.php, template-parts/navigation.php
Fix for #147 
I also wrapped a few `get_the_title()` instances with `esc_html`, in places where adding `em` or `strong` tags would look bad (like the read more link)`
@ianbelanger79 I think I got them all 😄
=> Fix - Unnecessary use of escaping functions

template-parts/content-cover.php, template-parts/content.php
Adds a span to the page numbers of wp_link_pages, so that the numbers are aligned.
The span also has the class _page-number_ added for future changes.
Solves #125
4.9:
=> Add a span to page numbers

functions.php
Fixes #716 by adding a `body:not(.overlay-header)` check to the `.primary-menu ul` targeting in `twentytwenty_get_elements_array()`, matching existing targeting for the cover template.
=> Fix color issues on the Cover Template

template-parts/modal-menu.php, template-parts/navigation.php
Adds missing `navigation` roles to `<nav>` elements.
Fixes: #462
=> Add missing roles to <nav> elements

assets/css/editor-style-classic-rtl.css, assets/css/editor-style-classic.css, functions.php, style.css
Hello,
This is a minor PR to adjust the naming of the editors so they're always referred to with the lowercase as is the spelling convention in core. As well I replaced instances of Gutenberg for block editor.
Thanks
=> Naming fixes

searchform.php
There's no need to first check if the key is set, `empty()` already covers this and doesn't throw a warning.
=> Merge isset() and empty()

404.php, classes/class-twentytwenty-customize.php, classes/class-twentytwenty-walker-comment.php, comments.php, footer.php, functions.php, header.php, inc/template-tags.php, phpcs.xml.dist, template-parts/content-cover.php, template-parts/entry-author-bio.php, template-parts/entry-header.php, template-parts/modal-menu.php, template-parts/modal-search.php
This adjusts the PHPCS config to align with WordPress core. It also allows us to remove the `// phpcs:ignore: WordPress.Security.EscapeOutput.OutputNotEscaped -- core trusts translations` comments and the use of escaping functions around strings.
=> PHPCS: i18n functions are considered safe for core translations.

assets/css/editor-style-block.css, functions.php, inc/custom-css.php, style.css
- Adds the "Primary" (text) color to the block editor palette, so all content colors in `accent_accessible_colors` can be used when editing content in the block editor.
- Updates style.css with styling of the `.has-[color]-color` and `.has-[color]-background-color` classes for all of the content colors in the editor palette, with the default colors set.
- Updates `twentytwenty_get_elements_array` with the new `.has-[color]-color` and `.has-[color]-background-color` classes, so the block editor color palette classes are updated when the color settings in the Customizer are changed.
=> Update the block editor color palette and its color classes

README.md, readme.txt
Updates `readme.md` and `readme.txt` with licensing information about code brought over from Twenty Nineteen and Twenty Seventeen. Fixes #760.
=> Add licensing information for Twenty Seventeen and Twenty Nineteen

CONTRIBUTING.md, assets/css/editor-style-classic-rtl.css, assets/css/editor-style-classic.css, package-lock.json, package.json, postcss.config.js, style-rtl.css, style.css
This PR seeks to update the styles _vendor prefixes_ per the WordPress supported browsers:
https://make.wordpress.org/core/handbook/best-practices/browser-support/
The vendor prefixes are updated using [Autoprefixer]() with the [`@wordpress/browserslist-config`](https://github.com/WordPress/gutenberg/tree/master/packages/browserslist-config) [Browserslist](https://github.com/browserslist/browserslist) configuration by [postcss-cli](https://github.com/pirxpilot/postcss-cli)
Note: The primary _build_ npm command has been updated to `npm run build` instead of the previous `npm run build:rtl`, the new `npm run build` command first updates the CSS file vendor prefixes and then runs the `npm run build:rtl` script to update the RTL CSS
=> Update CSS and RTL CSS style vendor prefixes per WPCS

inc/template-tags.php
This uses a contextual translation for a very short string in the template thta is output before a list of one or more categories.
Fixes: #801
=> Use contextual translation for a short prefixing string

style.css
This makes sure the style rule added in #709 only affects the title section for targeting the RSS feed icon.
Fixed #836
=> Make the CSS for hiding the RSS icon stricter

functions.php, template-parts/content.php
Fixes https://github.com/WordPress/twentytwenty/issues/791.
Is there a reason why the theme wouldn't use the default output from the more tag? What it's trying to do seems similar to what the default output does. 
This fix uses the default output and modifies it so the styling is correct.
=> Fixed more tag output.

style-rtl.css, style.css
Now the current page ancestor menu is not highlighting. It should highlight.
It works for both menus (`page_menu` and `nav_menu`).
**Before screenshot:**
**After screenshot:**
---
Also, Fixed highlight the model menu page ancestor menu item.
**Before screenshot:**
**After screenshot:**
=> Fix: Current menu ancestor is not highlighting issue.

assets/js/color-calculations.js
The previous implementation had a flaw that this PR fixes.
We were previously calculating the "score" of a color by multiplying the backround-contrast with the surrounding-text contrast. Then we were sorting the array of colors highest score first, and we were returning the item with the highest value.
This new version does something a lot better:
It calculates the score for colors by comparing them to the desired values for AAA compliance.
So the score is calculated like this now:
* If contrast with background is below 7, get the difference with the desired value (`7 - contrast`).
* If contrast with surrounding text is below 3, get the difference with the desired value (`3 - contrast`).
* return the sum of the `diff` values
* Sort by smaller score
The "score" is now …
=> Improve color calculations

inc/template-tags.php
In the AMP plugin there are links to in the classic publish metabox for viewing and editing a given URL, looking like this:
> <img width="277" alt="Screen Shot 2019-10-17 at 09 18 47" src="https://user-images.githubusercontent.com/134745/67027913-48a98600-f0bf-11e9-915b-34bf0714d634.png">
When Twenty Twenty is active, this appears broken:
> <img width="277" alt="Screen Shot 2019-10-17 at 09 18 31" src="https://user-images.githubusercontent.com/134745/67027941-52cb8480-f0bf-11e9-9491-1450f1712bc5.png">
The `twentytwenty_edit_post_link` function should short-circuit when `is_admin()`. This PR implements that change.
Introduced in #449.
=> Prevent filtering edit_post_link in the admin

style-rtl.css, style.css
This removes the underline that appears when hovering over an arrow, which can be found as part of the Post Navigation at the bottom of a post. The rest of the link will be underlined if hovered over the arrow, so I doubt this is an accessibility problem either, but it fixes #899.
**Before:**
**After:**
=> Post Navigation: Remove Underline for Arrows

style-rtl.css, style.css
This PR overrides the margin of the button block inside a cover block (which is why the extra `.entry-content` is necessary).
Fixes #917
**Before:**
**After:**
=> Fix: Aligned Button Block in Cover Block

assets/js/index.js
=> touch devices: open submenus on the desktop horizontal menu

functions.php, inc/custom-css.php
The CSS output in `custom-css.php` was using the `background` shorthand instead of `background-color` when setting the background color of elements. The caused other properties being unintentionally overwritten, like the `background-repeat` and `background-size` on cover blocks with an image and color set (see #957).
This PR replaces all uses of the `background` shorthand with `background-color`, in both `twentytwenty_get_customizer_css()` and `twentytwenty_get_elements_array()`.
Fixes #957.
=> Replace background shorthand with background-color in custom-css.php

style-rtl.css, style.css
Adds a very basic 1px dotted outline for input fields when they are focused.
This outline will be inconsistent for Chrome users. Ideally the outline should be consistent across the entire theme, not only for input fields, and independent on browsers.
Quick fix for https://github.com/WordPress/twentytwenty/issues/975
=> Update outline for input fields

functions.php
To avoid parsing the starter content on every single page request, we only
add the theme support for the starter content when `is_customizer_preview()` is
true.
Fixes #973
=> Load the starter content only when within the customizer

style-rtl.css, style.css
This PR contains fixes for the Columns block issues created by @yannickiki earlier today.
Fixes #963 and #961 by removing the paragraph-only padding used for the first and last columns in full-width columns blocks previously, and replaces it with a horizontal padding on the block as a whole. This made it possible to reduce the amount of CSS quite a bit, since it removed the need for different solutions for different breakpoints.
Before | After
------------ | -------------
Fixes #960 by adjusting the spacing between stacked Columns blocks between `782px` and `999px`. Also tweaked the margin on desktop, to make the horizontal margin between stacked columns blocks `32px` (same as the gutter) on all screen sizes.
Before | After
------------ | -------------
=> Fixes for the Columns block

inc/starter-content.php
This pulls in PR #955 which fixes a problem with some content not being reachable due to menu configurations. It also replicates the same menu entries in the expanded location to demonstrate it's abilities.
=> Garrett eclipse starter content mobile menu

style.css
This prevents an issue that causes screen readers to loose the spaces 
between words and read everything consecutively, with no word breaks, in 
a statement.
This is an attempted fix for #972 but with the one caveat noted in this comment: https://github.com/WordPress/twentytwenty/issues/972#issuecomment-551935050
=> Reset the word-break property on `.screen-reader-text`

functions.php
By default `Small` was displayed in selector as the font size when in reality `Regular` was the size that was in use for the text.
This PR only changes the slug from `regular` (name remains 'Regular') to `normal` allowing alphabetical sorting to handle displaying 'Regular' by default in dropdown to match the text size.
=> Swap slug for `regular` font size to `normal` so it shows as default

assets/js/index.js, style.css
In #949 changes were merged to fix #790, the inability to access a submenu item of the Desktop Horizontal Menu on tablet (>1000px). However, I [found](https://github.com/WordPress/twentytwenty/pull/949#issuecomment-551220080) the fix is not working:
An alternative approach to adding JS to support touch interfaces is rather to use CSS, specifically media queries for interaction media features ([caniuse](https://caniuse.com/#feat=css-media-interaction), currently 92.57% of browsers globally).
An added benefit of using CSS here is that it will ensure that the nav menus work when JS is turned off in the browser (or it fails to load, or it is an AMP page). Nevertheless, since IE11 doesn't support this media query, perhaps some JS logic should be included to add a `touch-enabled` class name on …
=> Fix ability to expand nav submenus on large-viewport touch interfaces

assets/css/editor-style-block-rtl.css, style-rtl.css, style.css
This PR fixes some of the inconsistencies between the editor and the front end after merging #701. 
It allows left/right floated images to look more like what appears in the editor, although it isn’t a perfect 100% match yet. On the frontend, Twenty Twenty resizes the images to make them fit within the layout properly. The editor’s flexible image widths UI, prevent is from replicating the same in the editor. But despite this, the left/right float settings are still respected in both the frontend and backend and so we can iterate on getting an exact 1:1 version later.
Editor | Before | After
------------|------------|------------
=> Improving floated content layout in nested groups.

assets/css/editor-style-block-rtl.css, assets/css/editor-style-block.css, style-rtl.css, style.css
**Before:**
**After:**
Fixes: #964
=> Add a11y friendly default text-colors when selecting a background-color.

style-rtl.css, style.css
Fixes the issue mentioned here after merging the new responsive width logic: 
https://github.com/WordPress/twentytwenty/pull/701#issuecomment-552655172
After fix:
=> Excluding pullquote block from width resize rules

style-rtl.css, style.css
Adds a missing exclusionary condition to allow wide align blocks to keep vertical margins when they **do not** have a background color.
See: #997
=> Adding `.has-background` excluding condition to wide and full group-blocks.

template-parts/content-cover.php
Removes the `.section-inner.thin` classes from the `.post-inner` element on the cover template, matching the structure used on `content.php` and fixing the alignment issue seen on http://2020.wordpress.net/about/.
=> Remove .section-inner.thin from the cover template

assets/css/editor-style-block-rtl.css, assets/css/editor-style-block.css, style-rtl.css, style.css
Fixes item from doc: _Resized image is not aligned correctly_
=> Make size margins `auto` for resized images

style-rtl.css, style.css
fixes item from doc: _The latest posts widget block isn’t aligned correctly_
=> Remove the 0 left-margin on some recent post blocks, uses auto instead

style-rtl.css, style.css
Fixes the full width template not being displayed full width.
=> Reimplemented Template: Full Width with the new entry content structure
