functions.php

Updates functions.php documentation to meet WordPress standards

Update doc-blocks and documentation

---

parts/page-header.php
style.css

Modifies the presentation of the entry content to better match the final design. This PR includes the following changes:
- Updated font sizes (sets entry content to 2.1rem at 700px)
- New heading styles
- Updated colors
- Input styles
- Base pullquote styles (plenty of more adjustments needed here, as well as in the other blocks)

Entry content adjustments

---

footer.php
style.css

This PR updates the footer structure to match the structure and style used in the design. Also includes styles for the social icons and base widget styles (widget specific styles are still needed).

New footer structure and style

---

footer.php

$s should be %s

---

README.md

Fixes #50 
This is only the first draft, which I've copied from https://github.com/WordPress/twentynineteen/blob/master/README.md and adjusted to the Twenty Twenty theme.

ADD #50: Add README.md

---

content.php

Remove superfluous closing `</div>`

---

CONTRIBUTORS.md

add fabiankaegy to contributors

---

style.css

#70 Align the `screen-reader-text`

---

README.md

We have the year 2018 in the copyright text, I guess we need to fix and make it 2019.

Fixed year 2018 to 2019 in readme.md file

---

functions.php

`body_class` is a filter, not action.
---
WordPress.org ID: rabmalin

Use proper hook for body_class

---

functions.php

Fixes #140 
---
WordPress.org: rabmalin

Remove unused code

---

functions.php
parts/classes/class-theme-customizer.php

fix like described in #155 
(+ .editorconfig coding standard changes)

remove toggle for using the cover modal on desktop

---

footer.php

#145: Remove Redundant echo

---

header.php

This PR fixes the WPCS notices that were present in the header.php file

Fix all WPCS notices in the header.php file

---

footer.php

Copyright notice year - Added context for translators

---

template-full-width.php

Only needed to add a file header to this file to satisfy PHPCS checks.

Fix all WPCS notices in the template-full-width.php file

---

pagination.php

Resolves some PHPCS notices in this file and adds contextual translation to pagination strings.

Fix all WPCS notices in the pagination.php file

---

parts/page-header.php

Does still contain a few errors, waiting on conformation of usage of closing PHP tags on same line or separate line

Fix all WPCS notices in the parts/page-header.php file

---

parts/modal-menu.php

Also replaced `:` and `endif;` with braces

Fix all WPCS notices in the parts/modal-menu.php file

---

footer.php

This is a first run, let me know if there is anything not correct

Fix all WPCS notices in the footer.php file

---

404.php

Add a file header comment and remove a superfluous space character

Fix all WPCS notices in the 404.php file

---

comments.php

Add a file header comment and some comment ending fullstops. Almost missed those full stops again though :s

Fix all WPCS notices in the comments.php file

---

style.css

Fixes #183 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

UPDATE #183: Adjust font size

---

classes/class-twentytwenty-customize.php
header.php
inc/template-tags.php

UPDATE #212-2: Adjust search button option

---

classes/class-twentytwenty-customize.php
header.php
inc/template-tags.php

Reverts WordPress/twentytwenty#252

Revert "UPDATE #212-2: Adjust search button option"

---

classes/class-twentytwenty-customize.php
header.php
inc/template-tags.php

Fixes #212 
Feedback from https://github.com/WordPress/twentytwenty/pull/252#pullrequestreview-288320245 and https://github.com/WordPress/twentytwenty/pull/252#issuecomment-531479146 have been implemented as well.

UPDATE #212-3: Adjust search button option

---

style.css

Includes a bunch of updates to the widget styles, with style changes for all built-in widgets.
Fixes #167 #126 
Also updates the search field to extend the entire width of the form by setting the label element to `width: 100%`, fixing #233

Update widget styles

---

header.php
index.php

UPDATE #270: Use } instead of endif for consistency reasons

---

style.css

Search untoggle fix - mobile

---

template-parts/content.php
template-parts/entry-header.php

Fixes #275 
<table>
<tr>
<td valign="top">Before:
<br><br>
</td>
<td valign="top">After:
<br><br>
</td>
</tr>
</table>
Please note that not all posts of the theme unit test file have excerpts which lead to strange looking gaps.

UPDATE #275: Adjust search result page

---

classes/class-twentytwenty-customize.php
template-parts/content.php

Adds an option to display excerpts in archives.
Renames the site header section to Theme Options.
Fixes #2

Add an option to display excerpts in archives

---

functions.php
style-rtl.css

This PR rebuilds the RTL stylesheet after #65 was merged and sets the theme to output it.

RTL stylesheet rebuild

---

inc/template-tags.php

Fixes #311 
<table>
<tr>
<td>WP Admin:
<br><br>
</td>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

UPDATE #311: Update Author Based On Profile Setting

---

style.css

Reduce the size of the drop cap in the front-end styles. Fixes #312.

Adjust font size of drop cap on front-end

---

functions.php
template-parts/content-cover.php

- `add_image_size` handle should use `-` instead of `_`.
- hex color should be lowercase

Functions.php - fix for small issues with consistency 

---

assets/js/index.js

Fix for #343
@andersnoren is something like this what you wanted? It fixes the main issue and removes/adds the overflow on body when needed.
I didn't really get the scroll to top part 😄 hope it's what you wanted.

Removed `twentytwenty.scrollLock` and fixed `overflow` issue

---

assets/js/index.js
style.css

UPDATE #366: Page jumps left/right when opening the search modal on desktop

---

classes/class-twentytwenty-customize.php
header.php
inc/template-tags.php

Regarding #335 #336
Also, made the html filterable.

Fixed title/logo issue with selective refresh for the Customizer

---

style.css

Fixed #371- Big, small have font-style instead of font-size

---

template-parts/entry-header.php

Fixed #369 - Search results shows manual excerpt twice

---

functions.php

Fixes #397 
**Before:**
`load_theme_textdomain( 'twentytwenty', get_template_directory() . '/languages' );`
**After:**
`load_theme_textdomain( 'twentytwenty' );`

UPDATE #397: Simplify text domain

---

style.css

Unwanted padding for author biography without gravatar

---

README.md
readme.txt
style.css

UPDATE/#376: Update meta in readme.txt, README.md & style.css

---

assets/js/index.js
header.php

Fix for #400
Will also fix the modal menu focus :) but might need some testing

Search input should be focused when the modal is opened

---

style-rtl.css
style.css

In anticipation of #363 being merged, this is the `style.css` file updated per WordPress Coding Standards.
It also includes the generated RTLCSS of these changes

Update `style.css` per WordPress Coding Standards

---

assets/css/font-awesome.css

In anticipation of #363 being merged, this is the `assets/css/font-awesome.css` file updated per WordPress Coding Standards.

Update `assets/css/font-awesome.css` per WordPress Coding Standards

---

assets/js/index.js

In anticipation of #363 being merged, this is the `assets/js/index.js` file updated per WordPress Coding Standards.

Update `assets/js/index.js` per WordPress Coding Standards

---

composer.json
composer.lock

This updates the `composer.json` and `composer.lock` files per WordPress Coding Standards

Update Composer files per WordPress Coding Standards

---

style.css

UPDATE #373: Add tags to style.css

---

classes/class-twentytwenty-walker-page.php

UPDATE #3: Add missing textdomain

---

inc/template-tags.php
style.css

Change responsive header layout when search is hidden

---

assets/css/font-awesome.css
style.css

Reverts WordPress/twentytwenty#429

Revert "Fix stylelint errors"

---

comments.php
style.css

Reduces the font size and margin of comment titles (as in "X Comment", "Leave a Reply"). Also: 
* Improves the styling of comment meta, including the "By post author" label
* Display the "X Comments" title when there are comments, if comments are closed
* If there are comments, and comments are closed, display a separator before the "Comments are closed" text
Fixes #396.

Reduce comment title font size, tweak comments style

---

assets/js/index.js

eslinted index.js (ES5)

---

functions.php

Removes background from menu and search toggles.
Removes accent from entry title, bottom footer and post meta.

Minor color updates

---

functions.php
template-parts/modal-menu.php
template-parts/modal-search.php

Updates the targeting of the color settings to include more elements. Also updates the icons of two toggle elements to inherit their fill from the parent element text color.

Update a11y color targeting

---

style.css

Fixed the color of the search modal close button when colors are set

---

functions.php

Fixes #505
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

UPDATE #505: Adjust color issue when using cover template

---

classes/class-twentytwenty-svg-icons.php
functions.php
template-parts/entry-header.php
template-parts/featured-image.php

UPDATE #509: Replace "Twenty Nineteen" with "Twenty Twenty"

---

style.css

When the admin bar is present.
Fix for #489

Fix - The cover on pages gets cut-off at the bottom

---

functions.php
inc/template-tags.php

Redo of #448 because of numerous merge conflicts

Redo remove if statements around hooks and filtered functions

---

functions.php

Redo of #519 because of merge conflicts

Fix toggle-text color

---

style.css

Fix left/right alignment of Image block

---

classes/class-twentytwenty-customize.php

UPDATE #517: Fix show search issue

---

assets/js/customize-controls.js
assets/js/customize-preview.js
functions.php

Redo of #523 due to merge conflicts

Update global JS variables

---

functions.php
style.css

Remove faux-button class.
Reduce skip link size. Minor restyling to better match core skip links.
Hopefully fixes #28

Update skip link style

---

assets/js/customize-preview.js
classes/class-twentytwenty-customize.php
functions.php

Fix for #537
Best viewed when a featured image is used.

Fix - Use selective refresh for cover overlay opacity and fixed background image

---

style.css

Fixed font size for comments content in mobile view
Fix for #549

Fix - Comment content font size is larger than running text on mobile

---

assets/css/editor-style-block-rtl.css
style-rtl.css
style.css

UPDATE #558: Remove “outline:none;”

---

classes/class-twentytwenty-customize.php

Fixes #495 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

UPDATE #495: Adjust theme options page

---

classes/class-twentytwenty-customize.php
functions.php

Fix - Remove old unused code for accent colors

---

style-rtl.css

UPDATE #614: Synch style-rtl.css with style.css

---

assets/js/index.js

Fix - JS error when no menu is assigned to the Desktop Expanded Menu location

---

style-rtl.css
style.css

UPDATE #629: Remove “text-align: justify;”

---

style-rtl.css

UPDATE WordPress#647: Synch style-rtl.css with style.css

---

footer.php

Fix output of social menu wrapper class

---

README.md

UPDATE #662: Add missing line breaks to README.md

---

style.css

Fixes #660 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

UPDATE #660: Improve list indents on small screens

---

assets/css/editor-style-block-rtl.css
style-rtl.css
style.css

Fix site header z-index issue on cover template

---

functions.php

UPDATE #682: Enable loading of child theme styles

---

404.php
index.php
singular.php
templates/template-cover.php

Addressing #703 , this PR moves the `<aside>` tag to outside the nesting of the `<main>` tag.

`<aside>` tag outside `<main>` tag

---

style-rtl.css

UPDATE #712: Synch style-rtl.css with style.css

---

assets/js/index.js
header.php

Fix - When closing the modals, focus should be moved back to the "opener" element

---

assets/js/index.js
template-parts/pagination.php

Fix - modals issue under 600px with admin bar enabled

---

header.php

Adds header role="banner"

---

404.php
footer.php
inc/template-tags.php
index.php
searchform.php
template-parts/entry-author-bio.php
template-parts/modal-search.php

I18N: Reduce use of context functions and improve translator comments

---

searchform.php

Replace uniqid() with wp_unique_id()

---

header.php
template-parts/modal-menu.php
template-parts/modal-search.php

The `data-toggle-screen-lock` attribute isn't used anymore, this PR will remove it.

Removed screen lock dataset

---

assets/js/index.js

Fix for #714 #81
@afercia @ianbelanger79 I hope this one is better 😄

Adding focus on "opener" buttons  using activeElement

---

style-rtl.css
style.css

Fixes #678 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

UPDATE #678: Adjust search outline

---

inc/template-tags.php

Moves some functions and adds new table of contents sections.

Rearranged template-tags.php

---

assets/css/editor-style-block-rtl.css
style-rtl.css

UPDATE #776: Synch RTL Styles

---

assets/css/editor-style-block.css

Includes improvements to the block editor styles, mostly related to nested layout blocks like groups and covers.
Before | After
------------ | -------------

Improvements to the block editor styles

---

classes/class-twentytwenty-customize.php

For #786 but there may be more text that needs to be updated.

Update and remove text strings in the customizer

---

assets/js/index.js

Fixed JS errors when Desktop Horizontal Menu isn't set

---

classes/class-twentytwenty-customize.php
functions.php
style.css

Reverts WordPress/twentytwenty#762

Revert "Adjust retina logo setting"

---

inc/custom-css.php

Reverts WordPress/twentytwenty#857

Revert "Removed some unused variables"

---

style-rtl.css
style.css
template-parts/entry-author-bio.php

Reorder author bio elements to avoid invalid html as pointed in #633. Remove unnecessary absolute positionings with a cleaner flex layout.

Fix html in author bio for #633

---

assets/js/color-calculations.js

I missed this in #872, there was a typo.

fix typo for color script

---

assets/css/editor-style-block-rtl.css

`npm run build` before rc2 patch

---

functions.php
template-parts/content.php

Fixes https://github.com/WordPress/twentytwenty/issues/901

Fixed more output when specifying custom text.

---

functions.php

credits gravityrail, byalextran

Update Ensure link to read more is preserved in Continue reading button 

---

README.md
readme.txt

Add credits for underscores to the readme files

---

readme.txt
style-rtl.css
style.css

This will ensure that GitHub is in sync with Trac after [Trac-48517](https://core.trac.wordpress.org/ticket/48517) is committed to SVN.

Fix and standardize headers for `Requires at least` and `Requires PHP`.

---

assets/css/editor-style-block-rtl.css
assets/css/editor-style-block.css
print.css
style-rtl.css
style.css

Add styles for the .has-normal-font-size class

---

functions.php

Should be the same as the others.

Fix text transform

---

footer.php

As it done throughout the theme.

Add end comment

---

CONTRIBUTORS.md

Add pierlon to contributors

---

.github/ISSUE_TEMPLATE/create-new-issues-on-trac.md

@pattonwebz: I created this issue template, in case someone missed your issue #991. What happens is, that if one creates a new issue, that person will see your text from #991.

Update issue templates

---

style-rtl.css
style.css

Needed to merge this change quickly. Thanks for the solution @briceduclos :-)

Remove margins for the group block when a background-color is se

---

style-rtl.css
style.css

Updates alignment classes to fix vanishing pull quote between 660px and 1000px.

Update alignment classes to fix vanishing pull quote

---

functions.php
style-rtl.css
style.css

fix item from doc: _Read More link is misaligned in some cases_

Add a wrapper around the read more button and apply a 1em top margin

---

style-rtl.css
style.css

Various final fixes:
- Fixes to alignleft/alignright within nested elements, like groups/cover blocks
- Combined double selectors for .read-more-button-wrap
- Fixed full-width template issue at 1280px

Various alignment fixes

---

style-rtl.css
style.css

Additional alignment adjustments, mostly to alignwide and alignfull with has-background.

More alignment adjustments

---

style-rtl.css
style.css

Fixed missing horizontal margin on alignleft/alignright above 1000px on the full width template.

Fixed Template: Full Width alignleft/alignright issue

---

style-rtl.css
style.css

Fixes the width of alignleft/alignright between 1280px and 1330px.

Alignment width fix

---

style-rtl.css
style.css

Fixes missing horizontal margins on alignleft/alignright in groups below 1280px.

Fix overwriting of alignleft/alignright margins in groups
